// Generated by scripts/api-routes.mjs from lib/services/attendance/attendance.controller.ts. Do not edit.
// POST /api/v1/attendance/check-in
export { forward as POST } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
