// Generated by scripts/api-routes.mjs from lib/auth/auth.controller.ts. Do not edit.
// GET /api/v1/auth/me
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
