// Generated by scripts/api-routes.mjs from lib/services/employees/employees.controller.ts. Do not edit.
// GET /api/v1/employees/form-options
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
