// Generated by scripts/api-routes.mjs from lib/services/dashboard/dashboard.controller.ts. Do not edit.
// GET /api/v1/search
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
