// Generated by scripts/api-routes.mjs from lib/services/users/users.controller.ts. Do not edit.
// POST /api/v1/users/:id/send-reset
export { forward as POST } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
