// Generated by scripts/api-routes.mjs from lib/services/roles/roles.controller.ts. Do not edit.
// GET /api/v1/permissions
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
