// Generated by scripts/api-routes.mjs from lib/services/settings/settings.controller.ts. Do not edit.
// DELETE /api/v1/holidays/:id
export { forward as DELETE } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
