// Generated by scripts/api-routes.mjs from lib/services/documents/documents.controller.ts. Do not edit.
// GET /api/v1/documents
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
