// Generated by scripts/api-routes.mjs from lib/services/leave/leave.controller.ts. Do not edit.
// PATCH, DELETE /api/v1/leave/types/:id
export { forward as PATCH, forward as DELETE } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
