// Generated by scripts/api-routes.mjs from lib/services/settings/settings.controller.ts. Do not edit.
// GET, PATCH /api/v1/settings/attendance
export { forward as GET, forward as PATCH } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
