// Generated by scripts/api-routes.mjs from lib/services/employees/employees.controller.ts. Do not edit.
// GET, PATCH /api/v1/me/profile
export { forward as GET, forward as PATCH } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
