// Generated by scripts/api-routes.mjs from lib/services/health/health.controller.ts. Do not edit.
// GET /api/v1/health/ready
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
