// Generated by scripts/api-routes.mjs from lib/services/organization/organization.controller.ts. Do not edit.
// GET /api/v1/departments/head-options
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
