// Generated by scripts/api-routes.mjs from lib/services/notifications/notifications.controller.ts. Do not edit.
// PATCH /api/v1/notifications/read-all
export { forward as PATCH } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
