// Generated by scripts/api-routes.mjs from lib/services/attendance/attendance.controller.ts. Do not edit.
// PATCH /api/v1/attendance/:id
export { forward as PATCH } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
