// Generated by scripts/api-routes.mjs from lib/services/organization/organization.controller.ts. Do not edit.
// GET, POST /api/v1/departments
export { forward as GET, forward as POST } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
