// Generated by scripts/api-routes.mjs from lib/services/audit/audit-log.controller.ts. Do not edit.
// GET /api/v1/audit-logs/:id
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
