// Generated by scripts/api-routes.mjs from lib/services/attendance/attendance.controller.ts. Do not edit.
// GET /api/v1/attendance/summary
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
