// Generated by scripts/api-routes.mjs from lib/services/users/users.controller.ts. Do not edit.
// PATCH /api/v1/users/:id/role
export { forward as PATCH } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
