// Generated by scripts/api-routes.mjs from lib/services/organization/organization.controller.ts. Do not edit.
// PATCH, DELETE /api/v1/positions/:id
export { forward as PATCH, forward as DELETE } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
