// Generated by scripts/api-routes.mjs from lib/services/leave/leave.controller.ts. Do not edit.
// POST /api/v1/leave/balances/allocate
export { forward as POST } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
