// Generated by scripts/api-routes.mjs from lib/services/documents/documents.controller.ts. Do not edit.
// PATCH, DELETE /api/v1/document-types/:id
export { forward as PATCH, forward as DELETE } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
