// Generated by scripts/api-routes.mjs from lib/services/users/users.controller.ts. Do not edit.
// GET /api/v1/users/form-options
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
