// Generated by scripts/api-routes.mjs from lib/services/employees/employees.controller.ts. Do not edit.
// POST /api/v1/employees/:id/deactivate
export { forward as POST } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
