// Generated by scripts/api-routes.mjs from lib/services/leave/leave.controller.ts. Do not edit.
// PATCH /api/v1/leave/balances/:id
export { forward as PATCH } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
