// Generated by scripts/api-routes.mjs from lib/services/team-profile/team-profile.controller.ts. Do not edit.
// POST, DELETE /api/v1/team-profile/me/photo
export { forward as POST, forward as DELETE } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
