// Generated by scripts/api-routes.mjs from lib/services/leave/leave.controller.ts. Do not edit.
// GET /api/v1/leave/balances
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
