// Generated by scripts/api-routes.mjs from lib/services/employees/employees.controller.ts. Do not edit.
// GET, PATCH, DELETE /api/v1/employees/:id
export { forward as GET, forward as PATCH, forward as DELETE } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
