// Generated by scripts/api-routes.mjs from lib/services/team-profile/team-profile.controller.ts. Do not edit.
// GET, PATCH /api/v1/team-profile/me
export { forward as GET, forward as PATCH } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
