// Generated by scripts/api-routes.mjs from lib/services/documents/documents.controller.ts. Do not edit.
// DELETE /api/v1/documents/:id
export { forward as DELETE } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
