#!/usr/bin/env node
/**
 * Writes one route file per API path under app/api/v1, from the NestJS controllers' decorators:
 * `@Controller('employees')` + `@Get(':id')` becomes app/api/v1/employees/[id]/route.ts exporting GET.
 * Each file forwards to the in-process API (lib/server/forward.ts), which still does the routing,
 * guards and validation, so the files only make every endpoint visible and reachable.
 *
 *   node scripts/api-routes.mjs          write the files, remove stale ones
 *   node scripts/api-routes.mjs --check  exit 1 if any file is missing, different or stale (CI)
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(root, 'app', 'api', 'v1');
const MARK = '// Generated by scripts/api-routes.mjs';
const check = process.argv.includes('--check');

const walk = (dir) =>
  readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : full.endsWith('.controller.ts') ? [full] : [];
  });

/** path ("employees/:id") -> { methods: Set, sources: Set } */
const routes = new Map();
for (const file of [...walk(join(root, 'lib', 'services')), ...walk(join(root, 'lib', 'auth'))]) {
  const source = relative(root, file).split(sep).join('/');
  let prefix = null;
  for (const m of readFileSync(file, 'utf8').matchAll(/@(Controller|Get|Post|Put|Patch|Delete)\(\s*(?:'([^']*)')?/g)) {
    const [, kind, arg = ''] = m;
    if (kind === 'Controller') {
      prefix = arg;
      continue;
    }
    if (prefix === null) throw new Error(`${source}: a route before any @Controller`);
    const path = [prefix, arg].filter(Boolean).join('/');
    const entry = routes.get(path) ?? { methods: new Set(), sources: new Set() };
    entry.methods.add(kind.toUpperCase());
    entry.sources.add(source);
    routes.set(path, entry);
  }
}

// Next allows one dynamic segment name per level, so the first name seen at a level is used for all
// (the names don't matter: the API reads the URL itself).
const slugAt = new Map();
const toDir = (path) => {
  const out = [];
  for (const segment of path.split('/')) {
    if (segment.startsWith(':')) {
      const key = out.join('/');
      if (!slugAt.has(key)) slugAt.set(key, segment.slice(1));
      out.push(`[${slugAt.get(key)}]`);
    } else out.push(segment);
  }
  return out.join('/');
};

const ORDER = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];
const wanted = new Map();
for (const path of [...routes.keys()].sort()) {
  const { methods, sources } = routes.get(path);
  const list = ORDER.filter((m) => methods.has(m));
  const content =
    `${MARK} from ${[...sources].sort().join(', ')}. Do not edit.\n` +
    `// ${list.join(', ')} /api/v1/${path}\n` +
    `export { ${list.map((m) => `forward as ${m}`).join(', ')} } from '@/lib/server/forward';\n\n` +
    `export const dynamic = 'force-dynamic';\n`;
  wanted.set(join(OUT, ...toDir(path).split('/'), 'route.ts'), content);
}

const existing = (() => {
  try {
    return walk2(OUT);
  } catch {
    return [];
  }
})();
function walk2(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk2(full) : name === 'route.ts' ? [full] : [];
  });
}

const problems = [];
for (const [file, content] of wanted) {
  let current = null;
  try {
    current = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  } catch {}
  if (current === content) continue;
  if (check) problems.push(`${relative(root, file)} is ${current === null ? 'missing' : 'out of date'}`);
  else {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
}
for (const file of existing) {
  if (wanted.has(file) || !readFileSync(file, 'utf8').startsWith(MARK)) continue;
  if (check) problems.push(`${relative(root, file)} has no endpoint any more`);
  else rmSync(file);
}

if (check && problems.length > 0) {
  console.error(`API route files are out of date. Run: node scripts/api-routes.mjs\n  ${problems.join('\n  ')}`);
  process.exit(1);
}
console.log(`${wanted.size} route files for ${[...routes.values()].reduce((n, r) => n + r.methods.size, 0)} endpoints${check ? ': up to date' : ''}`);
