// Generated by scripts/api-routes.mjs from lib/services/roles/roles.controller.ts. Do not edit.
// PUT /api/v1/roles/:id/permissions
export { forward as PUT } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
