// Generated by scripts/api-routes.mjs from lib/auth/auth.controller.ts. Do not edit.
// POST /api/v1/auth/login
export { forward as POST } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
