// Generated by scripts/api-routes.mjs from lib/services/notifications/notifications.controller.ts. Do not edit.
// GET /api/v1/notifications
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
