// Generated by scripts/api-routes.mjs from lib/services/documents/documents.controller.ts. Do not edit.
// GET, POST /api/v1/employees/:id/documents
export { forward as GET, forward as POST } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
