// Generated by scripts/api-routes.mjs from lib/services/leave/leave.controller.ts. Do not edit.
// GET, POST /api/v1/leave/requests
export { forward as GET, forward as POST } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
