// Generated by scripts/api-routes.mjs from lib/services/reports/reports.controller.ts. Do not edit.
// GET /api/v1/reports/:report
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
