// Generated by scripts/api-routes.mjs from lib/services/team-profile/team-profile.controller.ts. Do not edit.
// GET /api/v1/team-profile
export { forward as GET } from '@/lib/server/forward';

export const dynamic = 'force-dynamic';
